[package]
name = "peeler"
version = "0.1.0"
authors = ["Sascha Grunert <mail@saschagrunert.de>"]

[dependencies]
clap = { version = "2", features = ["yaml"] }
log = "0"
mowl = "1"
peel-ip = "0"
pnet = "0"
